version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventaris_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4.3
    container_name: inventaris_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inventaris
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      # simpan data MySQL di folder host (tidak hanya di volume docker)
      - ./mysql_data:/var/lib/mysql
      # file init.sql hanya jalan kalau database kosong
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro

volumes:
  # optional, biar tidak ada konflik volume lama
  # db_data:
    